
    SELECT DATE_FORMAT(N.SALES_DATE, "%Y-%m-%d") SALES_DATE, N.PRODUCT_ID, N.USER_ID, N.SALES_AMOUNT
    FROM ONLINE_SALE N
    WHERE SALES_DATE LIKE "2022-03%"
UNION ALL
    SELECT DATE_FORMAT(F.SALES_DATE, "%Y-%m-%d") SALES_DATE, F.PRODUCT_ID, NULL USER_ID, F.SALES_AMOUNT
    FROM OFFLINE_SALE F
    WHERE SALES_DATE LIKE "2022-03%"
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;