SELECT R.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE), 2) SCORE
FROM REST_REVIEW R
JOIN REST_INFO I ON R.REST_ID = I.REST_ID
GROUP BY R.REST_ID
HAVING I.ADDRESS LIKE "서울%"
ORDER BY SCORE DESC, I.FAVORITES DESC;

# SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, (
#     SELECT ROUND(AVG(B.REVIEW_SCORE), 2) 
#     FROM REST_REVIEW B
#     WHERE B.REST_ID = A.REST_ID
# ) AS SCORE
# FROM REST_INFO A
# WHERE A.ADDRESS LIKE "서울%"
# ORDER BY SCORE DESC, A.FAVORITES DESC;
