# 

SELECT YEAR(ED.DIFFERENTIATION_DATE) YEAR, (
    (
        SELECT MAX(SIZE_OF_COLONY) 
        FROM ECOLI_DATA
        WHERE YEAR(DIFFERENTIATION_DATE) = YEAR
    ) - SIZE_OF_COLONY
) YEAR_DEV, 
ED.ID 
FROM ECOLI_DATA ED
ORDER BY YEAR, YEAR_DEV
