SELECT YEAR(ED1.DIFFERENTIATION_DATE) AS YEAR, 
(
    SELECT MAX(SIZE_OF_COLONY) FROM ECOLI_DATA ED2
    WHERE YEAR(ED2.DIFFERENTIATION_DATE) = YEAR(ED1.DIFFERENTIATION_DATE)
) - ED1.SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA ED1
ORDER BY YEAR ASC, YEAR_DEV ASC;