SELECT B.ID, A.FISH_NAME, B.LENGTH FROM FISH_NAME_INFO A
JOIN FISH_INFO B ON A.FISH_TYPE = B.FISH_TYPE
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH 
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) C
ON B.FISH_TYPE = C.FISH_TYPE AND B.LENGTH = C.LENGTH
ORDER BY B.ID





# SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH 
# FROM FISH_INFO
# GROUP BY FISH_TYPE