SELECT ST.SCORE, HE.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL 
FROM HR_EMPLOYEES HE
JOIN HR_GRADE HG ON HE.EMP_NO = HG.EMP_NO
JOIN (
    SELECT EMP_NO, SUM(HG.SCORE) SCORE 
    FROM HR_GRADE HG
    GROUP BY EMP_NO
) ST ON HE.EMP_NO = ST.EMP_NO
WHERE ST.SCORE = (
    SELECT MAX(S.SCORE) FROM (
        SELECT EMP_NO, SUM(HG.SCORE) SCORE 
        FROM HR_GRADE HG
        GROUP BY EMP_NO
    ) S
)
GROUP BY HE.EMP_NO
