-- 코드를 입력하세요
-- 게시글 제목, 게시글 ID, 댓글 ID, 댓글 작성자 ID, 댓글 내용, 댓글 작성일
# SELECT a.TITLE, a.BOARD_ID, b.REPLY_ID, b.WRITER_ID, b.CONTENTS, date_format(b.CREATED_DATE, "%Y-%m-%d") as CREATED_DATE
# from USED_GOODS_BOARD a
# join USED_GOODS_REPLY b
# on a.BOARD_ID = b.BOARD_ID
# where b.CREATED_DATE between DATE("2022-10-01") and DATE("2022-10-31")
# order by CREATED_DATE, a.TITLE
SELECT
b.TITLE,
b.BOARD_ID,
r.REPLY_ID,
r.WRITER_ID,
r.CONTENTS,
DATE_FORMAT(r.CREATED_DATE, "%Y-%m-%d")
FROM USED_GOODS_BOARD b JOIN USED_GOODS_REPLY r
ON b.BOARD_ID = r.BOARD_ID
WHERE b.CREATED_DATE BETWEEN "2022-10-01" AND "2022-10-31"
ORDER BY r.CREATED_DATE, b.TITLE;