-- 코드를 입력하세요
-- SELECT A.TITLE
--      , A.BOARD_ID
--      , B.REPLY_ID
--      , B.WRITER_ID
--      , B.CONTENTS
--      , TO_CHAR(B.CREATED_DATE, 'YYYY-MM-DD') AS  CREATED_DATE
--   FROM USED_GOODS_BOARD A, USED_GOODS_REPLY B
--  WHERE A.BOARD_ID = B.BOARD_ID
--    AND TO_CHAR(B.CREATED_DATE, 'YYYY-MM') = '2022-10'
--  ORDER BY B.CREATED_DATE ASC, A.TITLE ASC;

SELECT B.TITLE
,      B.BOARD_ID
,      R.REPLY_ID
,      R.WRITER_ID
,      R.CONTENTS
,      TO_CHAR(R.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD B
,    USED_GOODS_REPLY R
WHERE TO_CHAR(B.CREATED_DATE, 'YYYY-MM') = '2022-10'
AND B.BOARD_ID = R.BOARD_ID
ORDER BY R.CREATED_DATE, B.TITLE;