SELECT S.DEPT_ID, HD.DEPT_NAME_EN, S.AVG_SAL FROM HR_DEPARTMENT HD
JOIN (SELECT DEPT_ID, ROUND(AVG(SAL)) AS AVG_SAL
FROM HR_EMPLOYEES HE
GROUP BY DEPT_ID) S ON S.DEPT_ID = HD.DEPT_ID
ORDER BY AVG_SAL DESC
